site_name: Create® 3 Docs
site_description: 'Documentation for the iRobot® Create® 3 robot'
site_author: 'iRobot'
#site_url: http://edu.irobot.com/create3/

repo_name: 'iRobotEducation/create3_docs'
repo_url: 'https://github.com/iRobotEducation/create3_docs'

edit_uri: 'edit/main/docs/'

docs_dir: docs/

theme:
  name: material
  custom_dir: theme_overrides
  logo: assets/irobot_symbol_white.png
  favicon: assets/irobot_symbol_green.png

extra_css:
  - stylesheets/irobot-palette.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/iRobotEducation
    - icon: fontawesome/brands/github
      link: https://github.com/iRobotEducation
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/iRobotEducation
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/irobot/
  analytics:
    provider: google
    property: G-9QX6GHMSD7

copyright: Copyright &copy; 2021-2023 iRobot Corporation. ​​All Rights Reserved.

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list

plugins:
  - search
  - macros

nav:
    - Home: index.md
    - Hardware:
      - Overview: hw/overview.md
      - Mechanical: hw/mechanical.md
      - Electrical:
        - Electrical Overview: hw/electrical.md
        - Buttons and Light Ring: hw/face.md
        - Adapter Board: hw/adapter.md
      - Printable Accessories:
        - Compute Boards: hw/print_compute.md
        - Create® 3 Caster: hw/print_casters.md
        - Generic Mounts: hw/print_generic.md
        - Sensor Mounts: hw/print_sensor_mounts.md
    - Webserver:
      - Overview: webserver/overview.md
      - Home: webserver/home.md
      - Connect: webserver/connect.md
      - Update: webserver/update.md
      - Logs: webserver/logs.md
      - Application: webserver/application.md
      - Beta Features:
        - Serial Port Forward: webserver/serial-config.md
        - Set Date and Time: webserver/set-datetime.md
        - Edit ntp.conf: webserver/edit-ntp-conf.md
        - Restart ntpd: webserver/restart-ntpd.md
        - Set Wired Subnet: webserver/set-wired-subnet.md
        - Override RMW Profile: webserver/rmw-profile-override.md
      - About: webserver/about.md
    - Setup:
      - Connect to Wi-Fi: setup/provision.md
      - Multi-Robot Setup: setup/multi-robot.md
      - ROS 2 Setup:
        - Galactic on Ubuntu 20: setup/ubuntu2004.md
        - Humble on Ubuntu 22: setup/ubuntu2204.md
        - Run with Docker: setup/docker.md
        - Middleware Config: setup/xml-config.md
        - Network Recommendations: setup/network-config.md
      - Add a Compute Board:
        - NavQPlus by NXP®:
          - Hookup Guide: hw/navqplus_hookup.md
          - Software Config: setup/navqplus.md
        - NVIDIA® Jetson™:
          - Hookup Guide: hw/jetson_hookup.md
          - Software Config: setup/jetson.md
        - Raspberry Pi®:
          - Hookup Guide: hw/rpi_hookup.md
          - Galactic Config: setup/pi4galactic.md
          - Humble Config: setup/pi4humble.md
        - Network Time Protocol: setup/compute-ntp.md
      - Fast DDS Discovery Server: setup/discovery-server.md
    - APIs:
      - ROS 2 Interface: api/ros2.md
      - Docking: api/docking.md
      - Drive Goals: api/drive-goals.md
      - Hazards: api/hazards.md
      - Odometry: api/odometry.md
      - Reflexes: api/reflexes.md
      - Safety: api/safety.md
      - User Interface: api/ui.md
      - Wall Follow: api/wall-follow.md
    - Simulator:
      - Using the Simulator: sim/setup.md
    - Software Examples:
      - Actuators via CLI: examples/actuators-cli.md
      - Sensors via CLI: examples/sensors-cli.md
      - Navigation Apps: examples/create3_examples.md
    - Firmware Releases:
      - Overview: releases/overview.md
      - Galactic:
        - G.5.2: releases/g_5_2.md
        - Older:
          - G.1.1: releases/g_1_1.md
          - G.2.2: releases/g_2_2.md
          - G.3.1: releases/g_3_1.md
          - G.4.1: releases/g_4_1.md
          - G.4.3: releases/g_4_3.md
          - G.4.4: releases/g_4_4.md
          - G.4.5: releases/g_4_5.md
          - G.5.1: releases/g_5_1.md
      - Humble:
        - H.2.2: releases/h_2_2.md
        - Older:
          - H.0.0: releases/h_0_0.md
          - H.1.0: releases/h_1_0.md
          - H.1.1: releases/h_1_1.md
          - H.1.2: releases/h_1_2.md
          - H.2.1: releases/h_2_1.md
